version: '3.8'

services:
  # Servicio 1: Nuestra Aplicación
  app:
    build: . # Construye la imagen usando el Dockerfile del directorio actual
    container_name: tp_app_contenedor
    ports:
      - "3000:3000" # Mapea el puerto 3000 de tu PC al 3000 del contenedor
    environment:
      - DB_HOST=db
      - DB_USER=usuario_tp
      - DB_PASSWORD=password_tp
      - DB_NAME=base_tp
    depends_on:
      - db # Asegura que la BD inicie antes que la app
    volumes:
      - ./backend:/usr/src/app # <-- Cambiar "." por "./backend"
      - /usr/src/app/node_modules # Evita sobreescribir los módulos instalados

  # Servicio 2: Persistencia (Base de Datos PostgreSQL)
  db:
    image: postgres:15-alpine # Imagen oficial de PostgreSQL
    container_name: tp_db_contenedor
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario_tp
      POSTGRES_PASSWORD: password_tp
      POSTGRES_DB: base_tp
    volumes:
      - db_data:/var/lib/postgresql/data # Volumen para que los datos no se borren al apagar Docker

# Declaración del volumen nombrado
volumes:
  db_data: